// components/Modal.tsx
import { motion } from "framer-motion";
import type { JSX } from "react";
import React from "react";

interface ModalProps {
  onClose: () => void;
}

export default function Modal({ onClose }: ModalProps): JSX.Element {
  return (
    <motion.div
      className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 px-4"
      onClick={onClose}
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
    >
      <motion.div
        className="bg-white/10 backdrop-blur-xl p-6 md:p-8 rounded-2xl max-w-xl w-full text-white shadow-[0_8px_32px_rgba(0,0,0,0.5)] border border-white/15 max-h-[90vh] overflow-y-auto"
        onClick={(e: React.MouseEvent<HTMLDivElement>) => e.stopPropagation()}
        initial={{ scale: 0.9, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        exit={{ scale: 0.9, opacity: 0 }}
        transition={{ type: "spring", stiffness: 300, damping: 25 }}
      >
        <h2 className="text-2xl md:text-3xl font-black text-[--color-iron-gold] italic uppercase">
          Welcome to IronBuddy
        </h2>

        <p className="text-gray-300 mt-4 text-sm leading-relaxed font-semibold">
          Before you begin, please read and accept our Health & Liability Disclaimer.
        </p>

        <div className="mt-4 space-y-4 text-sm text-white leading-relaxed">
          <p>
            IronBuddy provides AI-generated fitness and nutrition suggestions for{" "}
            <span className="text-white font-semibold">informational purposes only</span>. The content
            produced by IRON does not constitute medical advice, diagnosis, or treatment and is{" "}
            <span className="text-white font-semibold">
              not a substitute for professional medical, nutritional, or fitness guidance
            </span>{" "}
            from a qualified practitioner.
          </p>

          <p className="text-gray-300 font-semibold">By clicking "I Agree" you confirm that:</p>

          <ul className="space-y-2 list-none">
            {[
              "You are 18 years of age or older, or have obtained parental/guardian consent.",
              "You have consulted a physician before beginning any exercise or diet program, or accept full responsibility for not doing so.",
              "You understand that physical exercise carries inherent risk of injury or death and voluntarily assume all such risks.",
              "You understand that recommendations are generated by an AI and may not account for your full medical history.",
            ].map((item, i) => (
              <li key={i} className="flex gap-2">
                <span className="text-[--color-iron-gold] shrink-0 mt-0.5">▸</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>

          <p className="text-xs text-white/60 border-t border-white/10 pt-4">
            The developer of IronBuddy accepts <span className="text-white">no liability</span> for
            any injury, illness, loss, or damage arising directly or indirectly from use of this
            application or its AI-generated content. Use at your own risk.
          </p>
        </div>

        <button
          onClick={onClose}
          className="mt-6 w-full py-3 bg-[--color-iron-gold] text-black font-black rounded-lg uppercase
            hover:bg-yellow-200 hover:shadow-[0_0_20px_rgba(253,224,71,0.5)] hover:scale-[1.02] active:scale-95 transition-all duration-200"
        >
          I Agree
        </button>
      </motion.div>
    </motion.div>
  );
}
