# Generated by Django 6.0.3 on 2026-03-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='disclaimer_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
