# Generated by Django 6.0.3 on 2026-03-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_weight_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='community_visible',
            field=models.BooleanField(default=False),
        ),
    ]
