# Generated by Django 6.0.3 on 2026-03-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_community_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='excluded_ingredients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_ingredients',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
