# Generated by Django 6.0.3 on 2026-03-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_ingredient_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommeal',
            name='ingredients',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
