# Generated by Django 6.0.3 on 2026-03-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_workoutsession_notes_bodymeasurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('body_part', models.CharField(blank=True, max_length=100)),
                ('target', models.CharField(blank=True, max_length=100)),
                ('secondary_muscles', models.JSONField(default=list)),
                ('equipment', models.CharField(blank=True, max_length=100)),
                ('gif_url', models.URLField(blank=True, max_length=500)),
                ('instructions', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
