# Generated by Django 6.0.3 on 2026-03-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_exercise_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='wger_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='exercise',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
