# Generated by Django 6.0.3 on 2026-03-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_profile_picture_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.TextField(blank=True),
        ),
    ]
